packages:
  - backend
  - frontend
  - mobile
  - contracts
savePrefix: ''
engineStrict: true
autoInstallPeers: true
strictPeerDependencies: true
strictDepBuilds: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.21'
  - '@expo/fingerprint@0.20.12'
  - '@expo/router-server@57.0.9'
  - '@testing-library/user-event@14.6.7'
  - babel-preset-expo@57.0.10
  - expo-asset@57.0.16
  - expo-constants@57.0.17
  - expo-font@57.0.3
  - expo-modules-core@57.0.15
  - expo-modules-jsi@57.0.7
  - expo-notifications@57.0.16
  - expo-secure-store@57.0.3
  - expo@57.0.19
  - nestjs-pino@5.1.0
  - typeorm@1.1.1
  - viem@2.56.3
allowBuilds:
  '@google/genai@2.20.0': false
  '@parcel/watcher@2.6.0': true
  '@scarf/scarf@1.4.0': false
  '@swc/core@1.16.1': true
  'argon2@0.45.1': true
  'cpu-features@0.0.10': false
  'esbuild@0.28.2': true
  'msgpackr-extract@3.0.4': false
  'protobufjs@7.6.6': false
  'ssh2@1.17.0': false
  'unrs-resolver@1.12.2': true
