import type { CSSProperties } from 'react';
import type { ThemeConfig } from 'antd';

export const colorPalette = {
  canvas: '#f3f0e9',
  surface: '#fdfbf6',
  surfaceSelected: '#f1efea',
  subtle: '#f2ede4',
  text: '#1c1a17',
  textSecondary: '#52493c',
  muted: '#52493c',
  textDisabled: '#6e6253',
  border: '#a9977a',
  borderHover: '#5c5246',
  borderDecorative: '#e4dfd3',
  primary: '#a8792e',
  primaryHover: '#8f6726',
  primaryDark: '#8a611f',
  link: '#8a611f',
  linkHover: '#75531e',
  onPrimary: '#000000',
  sidebar: '#1e1b17',
  sidebarBorder: '#2e2a24',
  sidebarSelected: '#2e2a24',
  sidebarText: '#fbf8f2',
  sidebarMuted: '#b9ad98',
  baseWhite: '#fffdf8',
  dataQuota: '#574e40',
  infoSurface: '#e9f1f5',
  infoBorder: '#b7cfda',
  infoText: '#35586b',
  successSurface: '#e7f4ec',
  successBorder: '#a9d9bc',
  successText: '#1f6f46',
  warningSurface: '#fbf0d6',
  warningBorder: '#e8c468',
  warningText: '#7a5200',
  errorSurface: '#fbeaea',
  errorBorder: '#e7acac',
  errorText: '#9b2226',
  realtimeSurface: '#e3f3f3',
  realtimeBorder: '#a8d6d8',
  realtimeText: '#146670',
  moduleSurface: '#e4dfd3',
  moduleBorder: '#e4dfd3',
  moduleText: '#52493c',
  neutralSurface: '#e4dfd3',
  neutralBorder: '#e4dfd3',
  neutralText: '#52493c',
  commerceSurface: '#e4dfd3',
  commerceBorder: '#e4dfd3',
  commerceText: '#52493c',
} as const;

type CssVariableName = `--${string}`;
type ThemeCssVariables = CSSProperties & Record<CssVariableName, string>;

export const themeCssVariables: ThemeCssVariables = {
  '--canvas': colorPalette.canvas,
  '--surface': colorPalette.surface,
  '--surface-selected': colorPalette.surfaceSelected,
  '--bg-subtle': colorPalette.subtle,
  '--text': colorPalette.text,
  '--text-secondary': colorPalette.textSecondary,
  '--muted': colorPalette.muted,
  '--text-disabled': colorPalette.textDisabled,
  '--border': colorPalette.border,
  '--border-hover': colorPalette.borderHover,
  '--border-decorative': colorPalette.borderDecorative,
  '--control': colorPalette.border,
  '--control-hover': colorPalette.borderHover,
  '--primary': colorPalette.primary,
  '--primary-hover': colorPalette.primaryHover,
  '--primary-dark': colorPalette.primaryDark,
  '--link': colorPalette.link,
  '--link-hover': colorPalette.linkHover,
  '--on-primary': colorPalette.onPrimary,
  '--sidebar': colorPalette.sidebar,
  '--sidebar-border': colorPalette.sidebarBorder,
  '--sidebar-selected': colorPalette.sidebarSelected,
  '--sidebar-text': colorPalette.sidebarText,
  '--sidebar-muted': colorPalette.sidebarMuted,
  '--base-white': colorPalette.baseWhite,
  '--data-quota': colorPalette.dataQuota,
  '--info-surface': colorPalette.infoSurface,
  '--info-border': colorPalette.infoBorder,
  '--info-text': colorPalette.infoText,
  '--success-surface': colorPalette.successSurface,
  '--success-border': colorPalette.successBorder,
  '--success-text': colorPalette.successText,
  '--warning-surface': colorPalette.warningSurface,
  '--warning-border': colorPalette.warningBorder,
  '--warning-text': colorPalette.warningText,
  '--error-surface': colorPalette.errorSurface,
  '--error-border': colorPalette.errorBorder,
  '--error-text': colorPalette.errorText,
  '--realtime-surface': colorPalette.realtimeSurface,
  '--realtime-border': colorPalette.realtimeBorder,
  '--realtime-text': colorPalette.realtimeText,
  '--module-surface': colorPalette.moduleSurface,
  '--module-border': colorPalette.moduleBorder,
  '--module-text': colorPalette.moduleText,
  '--neutral-surface': colorPalette.neutralSurface,
  '--neutral-border': colorPalette.neutralBorder,
  '--neutral-text': colorPalette.neutralText,
  '--commerce-surface': colorPalette.commerceSurface,
  '--commerce-border': colorPalette.commerceBorder,
  '--commerce-text': colorPalette.commerceText,
};

export const themeRootCss = `:root{${Object.entries(themeCssVariables)
  .map(([name, value]) => `${name}:${String(value)}`)
  .join(';')}}`;

export const antTheme: ThemeConfig = {
  components: {
    Button: {
      defaultActiveBg: colorPalette.subtle,
      defaultActiveBorderColor: colorPalette.borderHover,
      defaultActiveColor: colorPalette.text,
      defaultBg: colorPalette.surface,
      defaultBorderColor: colorPalette.border,
      defaultColor: colorPalette.text,
      defaultHoverBg: colorPalette.subtle,
      defaultHoverBorderColor: colorPalette.borderHover,
      defaultHoverColor: colorPalette.text,
      primaryColor: colorPalette.onPrimary,
    },
  },
  token: {
    borderRadius: 6,
    colorBgBase: colorPalette.surface,
    colorBgContainer: colorPalette.surface,
    colorBgLayout: colorPalette.canvas,
    colorBorder: colorPalette.border,
    colorBorderSecondary: colorPalette.borderDecorative,
    colorError: colorPalette.errorText,
    colorInfo: colorPalette.infoText,
    colorLink: colorPalette.link,
    colorLinkActive: colorPalette.linkHover,
    colorLinkHover: colorPalette.linkHover,
    colorPrimary: colorPalette.primary,
    colorPrimaryActive: colorPalette.primaryHover,
    colorPrimaryHover: colorPalette.primaryHover,
    colorSuccess: colorPalette.successText,
    colorText: colorPalette.text,
    colorTextDescription: colorPalette.textSecondary,
    colorTextDisabled: colorPalette.textDisabled,
    colorTextPlaceholder: colorPalette.textDisabled,
    colorTextQuaternary: colorPalette.textDisabled,
    colorTextSecondary: colorPalette.textSecondary,
    colorTextTertiary: colorPalette.muted,
    colorWarning: colorPalette.warningText,
    fontFamily: '"IBM Plex Sans Variable", "Segoe UI", sans-serif',
  },
};
