import type { CSSProperties } from 'react';
import type { ThemeConfig } from 'antd';

export const colorPalette = {
  canvas: '#F3F7F8',
  surface: '#FFFFFF',
  surfaceSelected: '#FFE4D6',
  text: '#102A33',
  textSecondary: '#3D5159',
  muted: '#586A72',
  border: '#708791',
  primary: '#C33D1E',
  primaryDark: '#9A3412',
  onPrimary: '#FFFFFF',
  sidebar: '#0B2630',
  sidebarSelected: '#184653',
  sidebarText: '#F8FAFC',
  sidebarMuted: '#BED0D6',
  infoSurface: '#E0F2FE',
  infoBorder: '#3B82A6',
  infoText: '#075985',
  successSurface: '#DCFCE7',
  successBorder: '#4D9667',
  successText: '#166534',
  warningSurface: '#FEF3C7',
  warningBorder: '#B7791F',
  warningText: '#854D0E',
  errorSurface: '#FEE2E2',
  errorBorder: '#D15757',
  errorText: '#991B1B',
  moduleSurface: '#F3E8FF',
  moduleBorder: '#9A62C7',
  moduleText: '#6B21A8',
  neutralSurface: '#E5ECEF',
  neutralBorder: '#5F7680',
  neutralText: '#31464F',
  commerceSurface: '#FFF0E8',
  commerceBorder: '#C45A32',
  commerceText: '#8F2F13',
} as const;

type CssVariableName = `--${string}`;
type ThemeCssVariables = CSSProperties & Record<CssVariableName, string>;

export const themeCssVariables: ThemeCssVariables = {
  '--canvas': colorPalette.canvas,
  '--surface': colorPalette.surface,
  '--surface-selected': colorPalette.surfaceSelected,
  '--text': colorPalette.text,
  '--text-secondary': colorPalette.textSecondary,
  '--muted': colorPalette.muted,
  '--border': colorPalette.border,
  '--primary': colorPalette.primary,
  '--primary-dark': colorPalette.primaryDark,
  '--on-primary': colorPalette.onPrimary,
  '--sidebar': colorPalette.sidebar,
  '--sidebar-selected': colorPalette.sidebarSelected,
  '--sidebar-text': colorPalette.sidebarText,
  '--sidebar-muted': colorPalette.sidebarMuted,
  '--info-surface': colorPalette.infoSurface,
  '--info-border': colorPalette.infoBorder,
  '--info-text': colorPalette.infoText,
  '--success-surface': colorPalette.successSurface,
  '--success-border': colorPalette.successBorder,
  '--success-text': colorPalette.successText,
  '--warning-surface': colorPalette.warningSurface,
  '--warning-border': colorPalette.warningBorder,
  '--warning-text': colorPalette.warningText,
  '--error-surface': colorPalette.errorSurface,
  '--error-border': colorPalette.errorBorder,
  '--error-text': colorPalette.errorText,
  '--module-surface': colorPalette.moduleSurface,
  '--module-border': colorPalette.moduleBorder,
  '--module-text': colorPalette.moduleText,
  '--neutral-surface': colorPalette.neutralSurface,
  '--neutral-border': colorPalette.neutralBorder,
  '--neutral-text': colorPalette.neutralText,
  '--commerce-surface': colorPalette.commerceSurface,
  '--commerce-border': colorPalette.commerceBorder,
  '--commerce-text': colorPalette.commerceText,
};

export const themeRootCss = `:root{${Object.entries(themeCssVariables)
  .map(([name, value]) => `${name}:${String(value)}`)
  .join(';')}}`;

export const antTheme: ThemeConfig = {
  token: {
    borderRadius: 6,
    colorBgBase: colorPalette.surface,
    colorBgContainer: colorPalette.surface,
    colorBgLayout: colorPalette.canvas,
    colorBorder: colorPalette.border,
    colorBorderSecondary: colorPalette.border,
    colorError: colorPalette.errorText,
    colorInfo: colorPalette.infoText,
    colorLink: colorPalette.primaryDark,
    colorLinkActive: colorPalette.primaryDark,
    colorLinkHover: colorPalette.commerceText,
    colorPrimary: colorPalette.primary,
    colorPrimaryActive: colorPalette.primaryDark,
    colorPrimaryHover: colorPalette.primaryDark,
    colorSuccess: colorPalette.successText,
    colorText: colorPalette.text,
    colorTextDescription: colorPalette.textSecondary,
    colorTextPlaceholder: colorPalette.muted,
    colorTextQuaternary: colorPalette.muted,
    colorTextSecondary: colorPalette.textSecondary,
    colorTextTertiary: colorPalette.muted,
    colorWarning: colorPalette.warningText,
    fontFamily: '"IBM Plex Sans", "Segoe UI", sans-serif',
  },
};
